# Generated by Django 4.2.5 on 2023-12-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeImage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
