# Generated by Django 4.2.5 on 2023-12-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('home_title', models.CharField(max_length=100)),
                ('years_exp', models.CharField(max_length=20)),
            ],
        ),
    ]
