# Generated by Django 4.2.5 on 2023-12-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_websitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/serviceIcon')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='images',
            name='homeImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/website'),
        ),
    ]
